name: Build and test Android APK
on:
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Unit tests
        run: ./gradlew test --stacktrace
